---
- hosts: 127.0.0.1 
  connection: local
  vars:
    zsh_path: /usr/bin/zsh
    home_path: /home/hcavalle
    home_dir: /home/hcavalle
    tmp_dir: /home/hcavalle/Downloads
    ds_repo_dir: /home/hcavalle/ds/repos
    vim_bundle_dir: /home/hcavalle/.dotfiles/vim/bundle

  tasks:

    #- include: tasks/dev.yml 
    - include: tasks/dotfiles.yml 
    #- include: tasks/zsh.yml 
    #- debug: msg='Done.'
