---
- hosts: 127.0.0.1 
  connection: local
  vars:
    zsh_path: /usr/bin/zsh
    home_path: /home/hcavalle
    home_dir: /home/hcavalle
    tmp_dir: /home/hcavalle/Downloads
    ds_repo_dir: /home/hcavalle/ds/repos

  tasks:

    - name: Install base packages
      action: apt pkg={{item}} state=installed
      with_items:
        - zsh
        - screen
        - vim-gtk
        - ssh
        - w3m
        - surfraw
        - openvpn

      sudo: yes

    - include: tasks/dev.yml 
    - include: tasks/dotfiles.yml 
    - include: tasks/zsh.yml 
    - debug: msg='Done.'
