---
- hosts: 127.0.0.1 
  connection: local
  sudo: yes

  tasks:

    - name: Install base packages
      action: apt pkg={{item}} state=installed
      with_items:
        - zsh
        - screen
        - vim-gtk
        - ssh

    - include: tasks/dev.yml 
    - include: tasks/zsh.yml 
    - include: tasks/dotfiles.yml 
    - debug: msg='Done.'
