- hosts: local
  connection: local

  tasks:
    - name: add VirtualBox repo signing key
        yum_key: state=present
                     url=http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc

    - name: add virtualbox repo for precise
        yum_repository: repo='deb http://download.virtualbox.org/virtualbox/debian precise contrib'
            sudo: yes

    - name: Update yum package cache
      yum: update_cache=yes sudo=yes

    - name: Install base packages
      yum: name=$item state=latest
      with_items:
        - zsh
        - screen
        - vim-gtk
        - ssh

  - name: zsh facts
    shell: 'echo $SHELL'
    register: default_shell
    changed_when: False
    sudo: no

  - name: make zsh default
    shell:  chsh -s /bin/zsh 
    when: default_shell.stdout.find('/bin/zsh') == -1

  handlers:
    - name: start sshd
      service: name=sshd state=restarted
