---
# main.yml for deb base 
  - name: Install base packages
    apt-get: name=$item state=latest
    with_items:
      - curl
      - htop
      - openssl
      - pkg-config
      - build-essential
      - git
  - name: Install ruby language tools
    apt-get: name=$item state=latest
	with_items:
	    - python-pip
	    - curl
	    - nodejs
	    - nfs-kernel-server
	    - nfs-common
	    - rpcbind
	    - tmux
	    - npm
	    - libjpeg-dev
	    - libfreetype6-dev
	    - zlib1g-dev
	    - libpng12-dev
	    - python-dev
	    - libpq-dev
	    - python-dev
	  sudo: yes
