---
  - name: Install base packages
    action: apt pkg={{item}} state=installed
    with_items:
      - curl
      - htop
      - openssl
      - pkg-config
      - build-essential
      - git
      - tree
      - gnupg
      - zip
      - rsync
    sudo: yes

  - name: Install python language tools
    action: apt pkg={{item}} state=installed
    with_items:
      - python-pip
      - libjpeg-dev
      - libssl-dev
      - libfreetype6-dev
      - zlib1g-dev
      - libpng12-dev
      - python-dev
      - libpq-dev
      - python-dev
    sudo: yes

  - name: Install ruby language tools
    action: apt pkg={{item}} state=installed
    with_items:
      - ruby
      - ruby-dev
    sudo: yes

  - name: Install java tools
    action: apt pkg={{item}} state=installed
    with_items:
      - python-software-properties
    sudo: yes

  - name: add java oracle repo
    apt_repository: repo='ppa:webupd8team/java' state=present
    sudo: yes


  - name: Install java tools
    action: apt pkg={{item}} state=installed
    with_items:
      - default-jre
      - default-jdk
      - openjdk-7-jre
      - openjdk-7-jdk
      - python-software-properties
      - eclipse
    sudo: yes

  - name: Pip install stuff
    pip: name=virtualenv
  - name: Pip install aws stuff
    pip: name=awscli

  - name: install vbox and vagrant
    action: apt pkg={{item}} state=installed
    with_items: 
      - virtualbox
      - vagrant
      - virtualbox-dkms
    sudo: yes

  - name: download packer
    get_url: url='https://dl.bintray.com/mitchellh/packer/packer_0.7.5_linux_amd64.zip' dest={{ tmp_dir }}
    
    
  - name: unzip packer
    unarchive: src={{ tmp_dir }}/packer_0.7.5_linux_amd64.zip copy=false dest=/usr/bin
    sudo: yes

  - name: download terraform
    get_url: url='https://dl.bintray.com/mitchellh/terraform/terraform_0.4.2_linux_amd64.zip' dest={{ tmp_dir }}
    
  - name: unzip terraform
    unarchive: src={{ tmp_dir }}/terraform_0.4.2_linux_amd64.zip dest=/usr/bin 
    sudo: yes

  #- name: Clone all ds repos
  #  shell: sudo /bin/sh -c 'curl -u <token>:x-oauth-basic -s https://api.github.com/orgs/datascienceinc/repos\?per_page\=200 | ruby -rubygems -e `require "json"; JSON.load(STDIN.read).each { |repo| %x[git clone #{repo["ssh_url"]} ]}`'
