---
- apt: name=rcm state=installed
  sudo: yes

- name: Check rcm is installed
  stat: path=/usr/local/bin/rcup
  register: rcm_installed

- name: Check dotfiles exist
  stat: path=/home/hcavalle/.dotfiles
  register: dotfiles_installed

- name: Check out dotfiles repo
  git: repo=git@github.com:hcavalle/.dotfiles.git dest=/home/hcavalle/.dotfiles/
  when: dotfiles_installed.stat.exists == False 
    
- name: Checkout syntastic
  git: repo=git@github.com:scrooloose/syntastic.git dest={{ vim_bundle_dir }}/syntastic force=yes
    
- name: Checkout nerdtree
  git: repo=git@github.com:scrooloose/nerdtree.git dest={{ vim_bundle_dir }}/nerdtree  force=yes
    
- name: Checkout nerdcommenter
  git: repo=git@github.com:scrooloose/nerdcommenter.git dest={{ vim_bundle_dir }}/nerdcommenter  force=yes

  # clone ctrlp, vim-markdown, node, python-mode, ultisnips, vim-javascript syntax

- name: Apply dotfiles
  shell: rcup -f -d /home/hcavalle/.dotfiles/
